### ISSUE TITLE
Stems and affixes are unavaileble in *In-source documentation* after level reorg 

### ISSUE THREAD

**Issue by Trondtr** [giellalt/giellalt.github.io#15]
To repeat: Go to In-source documentation for any language model, e.g. https://giellalt.github.io/lang-smn/ . The `affixes` and `stems` catalogues are not expandable, and the files under them thus inaccessible.

**Comment by snomos** [comment]
Fixed in https://github.com/giellalt/giella-core/commit/ea0a06c819dae6688beea718303edad900309053

Each repo needs to be updated, but that should happen by itself over time as we work.
