### ISSUE TITLE
Add jekyll-spaceship to docu build

### ISSUE THREAD

**Issue by snomos** [giellalt/giellalt.github.io#5]
The Jekyll plugin [jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship#1-table-usage) can improve several aspects of the GitHub Pages documentation:

- flow charts and other diagrams from a simple text syntax
- more flexible tables
- graphs & pie charts from textual data
- and more

Unfortunately, it is not supported by default by GitHub Pages, and making it work is a bit of a hassle. I have looked at the following:

- https://github.com/jeffreytse/jekyll-jeffreytse-blog/blob/master/Gemfile
- https://www.moncefbelyamani.com/making-github-pages-work-with-latest-jekyll/
- https://jekyllrb.com/docs/plugins/installation/
- https://github.com/limjh16/jekyll-action-ts

I have so far tested with [lang-smn](https://gielalt.github.io/lang-smn). When it works, the following test page should be rendered as a simple graph:

- https://giellalt.github.io/lang-smn/Test.html

**Comment by flammie** [comment]
https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by snomos** [comment]
Thanks for the link, looks very promising 🙂  I am still not able to make it work, though.

**Comment by snomos** [comment]
I played with a dead-plain GH Pages test site here: https://dadmin-test.github.io/test-2/

But no joy.

**Comment by flammie** [comment]
hmm...

```mermaid
  graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```

this wokrs?

**Comment by snomos** [comment]
It does!! 😄  How come it does not in GitHub Pages??

**Comment by snomos** [comment]
> I played with a dead-plain GH Pages test site here: https://dadmin-test.github.io/test-2/
> 
> But no joy.

If I look at the same document as source code in the repository, it works exactly as expected:

https://github.com/dadmin-test/test-2/blob/new_branch1/index.md

This is strange - it seems to work everywhere BUT in GH Pages.

**Comment by snomos** [comment]
What about this demo?

```mermaid
sequenceDiagram
    participant dotcom
    participant iframe
    participant viewscreen
    dotcom->>iframe: loads html w/ iframe url
    iframe->>viewscreen: request template
    viewscreen->>iframe: html & javascript
    iframe->>dotcom: iframe ready
    dotcom->>iframe: set mermaid data on iframe
    iframe->>iframe: render mermaid
```

**Comment by snomos** [comment]
This is now solved, not by using Jekyll spaceship, but via [this GH action](https://github.com/divvun/compile-mermaid-markdown-action).

See e.g. https://giellalt.github.io/infra/docinfra.html for a working example.
